config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "dashboard#home"

  get "admins" => "admins#index", as: :admins

  resources :organizations, only: [:new, :create]
  get '/is_domain_available' => 'organizations#is_domain_available'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :organization

	validates :line1, presence: true, length: { maximum: 30 }
    validates :line2, length: { maximum: 30 }
    validates :city, presence: true, length: { maximum: 30}
    validates :state, length: { maximum: 30 }
    validates :country, presence: true, length: { maximum: 30 }
    validates :zipcode, presence: true, length: { minimum: 6, maximum: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_one :profile, inverse_of: :organization, dependent: :destroy
  has_one :address, inverse_of: :organization, dependent: :destroy

  accepts_nested_attributes_for :profile
  accepts_nested_attributes_for :address

  validates :org_name, presence: true, length: { maximum: 30 }
  validates :org_identifier, presence: true, length: { maximum: 30 }, format: { with: /\A[a-zA-Z0-9_]+\z/ }
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :organization

	validates :first_name, presence: true, length: { minimum: 3, maximum: 30 }
    validates :last_name, presence: true, length: { maximum: 50 }
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :organization
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	before_action :verify_admin_or_not

	def index
		if params[:org_name] || params[:created_by] || params[:country]
			@organizations = Organization.paginate(:page => params[:page], :per_page => 30).joins(:user, :address).where('email = ? OR country = ? OR org_name = ?', params[:created_by], params[:country], params[:org_name])
		else 
			@organizations = Organization.paginate(:page => params[:page], :per_page => 30)
		end
	end

	private

	def verify_admin_or_not
		unless current_user.is_admin
			flash[:notice] = 'You are not authorized to view this page.' 
	      	redirect_to root_path
	    end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource


  def after_sign_out_path_for(resource)
    new_user_session_path
  end


  private

  def layout_by_resource
    if devise_controller?
      "application"
    else
      "dashboard"
    end
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_action :authenticate_user!

  def home
  	if current_user.organization.nil?
  		redirect_to new_organization_path
  	end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

	before_action :authenticate_user!

	def new
		@organization = current_user.build_organization
		@organization.build_profile
		@organization.build_address
	end

	def create
		@organization = current_user.build_organization(organization_params)

		respond_to do |format|
			if @organization.save
				format.html { redirect_to root_url, notice: 'Organization was successfully created.' }
        		format.json { render :show, status: :created, location: @task }
        	else
        		format.html { render :new }
        		format.json { render json: @organization.errors, status: :unprocessable_entity }
			end
		end
	end 

	def is_domain_available
		status = Organization.find_by(org_name: params["organization_name"]).blank?
	    render json: status
	end

	private

	def organization_params
		params.require(:organization).permit(:org_name, :org_identifier, profile_attributes: [:first_name, :last_name], address_attributes: [:line1, :line2, :city, :state, :country, :zipcode])
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <%= form_tag admins_path, method: :get do %>
        <div class="row">
          <div class="col-md-3">
            <div class="form-group">
              <%= text_field_tag :org_name, nil, class: "form-control", placeholder: 'Org name' %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <%= text_field_tag :created_by, nil, class: "form-control", placeholder: 'Created by' %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <%= text_field_tag :country, nil, class: "form-control", placeholder: 'Country' %>
            </div>
          </div>
          <div class="col-md-3">
            <%= submit_tag "Search", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
  </div>
  </div>
</div>
<div class="row">
  <div class='col-md-12'>
  <table class='table' id='organization_table'>
    <thead>
      <th>ID</th>
      <th>Organization name</th>
      <th>Organization Identifier</th>
      <th>Created by</th>
      <th>Country</th>
    </thead>
    <tbody>
      <% @organizations.each do | org | %>
        <tr>
          <td><%= org.try(:id) %></td>
          <td><%= org.try(:org_name) %></td>
          <td><%= org.try(:org_identifier) %></td>
          <td><%= org.user.try(:email) %></td>
          <td><%= org.address.try(:country) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @organizations %>
  </div>
</div>

app/views/dashboard/home.html.erb
<h1>Thank for registering.
<p> We'all let you know once our product is ready.</p></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeedBack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <span class="notice text-center hide"><%= notice %></span>
    <span class="alert text-center hide"><%= alert %></span>

    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <title>Upcoming App</title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>

    <% dyn_controller = controller.controller_name %>
    <%= stylesheet_link_tag    'application', dyn_controller, media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', dyn_controller, 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <span class="notice hide"><%= notice %></span>
    <span class="alert hide"><%= alert %></span>

    <div class="wrapper">
      <%= render 'shared/dashboard/sidebar' %>
      <div class="main-panel">
        <%= render 'shared/dashboard/header' %>
        <div class="content">
          <div class="container-fluid">
            <div class="row">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/organizations/_form.html.erb
<div class="row">
    <div class="col-md-12">
      <div class="content">
            <%= simple_form_for(organization) do |f| %>
              <% if organization.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

                  <ul>
                  <% organization.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="row">
                <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">
                  <div class="form-group">
                    <%= f.input :org_name, label: false, input_html: { class: "form-control", required: true }, placeholder: "org name" %>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">
                  <div class="form-group">
                    <%= f.input :org_identifier, label: false, input_html: { class: "form-control", required: true, :readonly => true  } %>
                  </div>
                </div>
              </div>

              <%= f.simple_fields_for :profile do |p| %>
                <div class="row">
                  <div class="col-lg-offset-3 col-lg-3 col-md-offset-2 col-md-4">
                    <div class="form-group">
                      <%= p.input :first_name, label: false, input_html: { class: "form-control", required: true }, placeholder: "first name"  %>
                    </div>
                  </div>
                  <div class="col-lg-3 col-md-4">
                    <div class="form-group">
                      <%= p.input :last_name, label: false, input_html: { class: "form-control", required: true }, placeholder: "last name"  %>
                    </div>
                  </div>
                </div>
              <% end %>

              <%= f.simple_fields_for :address do |a| %>
                <div class="row">
                  <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">
                    <div class="form-group">
                      <%= a.input :line1, label: false, input_html: { class: "form-control", required: true }, placeholder: "line 1"  %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">
                    <div class="form-group">
                      <%= a.input :line2, label: false, input_html: { class: "form-control", required: true }, placeholder: "line 2" %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-offset-3 col-lg-3 col-md-offset-2 col-md-4">
                    <div class="form-group">
                      <%= a.input :city, label: false, input_html: { class: "form-control", required: true }, placeholder: "city" %>
                    </div>
                  </div>
                  <div class="col-lg-3 col-md-4">
                    <div class="form-group">
                      <%= a.input :state, label: false, input_html: { class: "form-control", required: true }, placeholder: "state" %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-offset-3 col-lg-3 col-md-offset-2 col-md-4">
                    <div class="form-group">
                      <%= a.input :country, label: false, :as => :string, input_html: { class: "form-control", required: true }, placeholder: "country" %>
                    </div>
                  </div>
                  <div class="col-lg-3 col-md-4">
                    <div class="form-group">
                      <%= a.input :zipcode, label: false, input_html: { class: "form-control", required: true, maxlength: 6 }, placeholder: "zipcode" %>
                    </div>
                  </div>
                </div>
              <% end %>

              <div class="row">
                <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8">
                  <%= f.button :submit, class: 'btn btn-primary' %>
                </div>
              </div>
            <% end %>
      </div>
    </div>
</div>

app/views/organizations/new.html.erb
<div class="content">
  <div class="container-fluid">
  	<div class="card">
	  	<div class="header">
	      <h2>New Organization</h2>
	    </div>
		<%= render 'form', organization: @organization %>
	</div>
  </div>
</div>

app/views/shared/dashboard/_header.html.erb
 <nav class="navbar navbar-default navbar-fixed">
   <div class="container-fluid">
       <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <%= link_to "Dashboard", root_path, class: "navbar-brand" %>
           <% if current_user.is_admin %>
            <%= link_to "Admin", admins_path, class: "navbar-brand" %>
           <% end %>
       </div>
       <div class="collapse navbar-collapse">
           <ul class="nav navbar-nav navbar-right">
               <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       <p>
                           Account
                           <b class="caret"></b>
                       </p>

                   </a>
                   <ul class="dropdown-menu">
                       <li><a href="#"><%=current_user.try(:email) %></a></li>
                       <li class="divider"></li>
                       <li>
                         <% if user_signed_in? %>
                           <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                         <% end %>
                       </li>
                   </ul>
               </li>
               <li class="separator hidden-lg"></li>
           </ul>
       </div>
   </div>
</nav>

app/views/shared/dashboard/_sidebar.html.erb
<div class="sidebar" data-color="red" data-image="<%= image_url('sidebar-5.jpg')%>">
   <div class="sidebar-wrapper">
       <div class="logo">
           <a href="http://www.creative-tim.com" class="simple-text">
                   Upcoming App
               </a>
       </div>

       <ul class="nav">
         
        </ul>
   </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>